package main

import (
	"fmt"
	_ "github.com/converge/my-bike-api/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger"
	"log"
	"net/http"
)

func version(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("1.0.0"))
}

// @title Titulo da sua API
// @version 1.0
// @description Descricão longa da sua API
// @termsOfService http://swagger.io/terms/
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:3001
// @BasePath /
func main() {
	r := chi.NewRouter()
	r.Get("/", version)
	r.Get("/swagger/*", httpSwagger.WrapHandler)
	fmt.Println("API Listening at http://localhost:3001")
	err := http.ListenAndServe(":3001", r)
	if err != nil {
		log.Fatalln(err)
	}
}