basePath: /
host: localhost:3001
info:
  contact: {}
  description: Descricão longa da sua API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Titulo da sua API
  version: "1.0"
paths: {}
swagger: "2.0"
